/* 
 * EmployeeManagementSystem API
 *
 * Simple web app with open API for Euristiq needs
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CompaniesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CompaniesApiTests
    {
        private CompaniesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CompaniesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompaniesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CompaniesApi
            //Assert.IsInstanceOfType(typeof(CompaniesApi), instance, "instance is a CompaniesApi");
        }

        
        /// <summary>
        /// Test V1CompaniesByIdDelete
        /// </summary>
        [Test]
        public void V1CompaniesByIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //instance.V1CompaniesByIdDelete(id);
            
        }
        
        /// <summary>
        /// Test V1CompaniesByIdGet
        /// </summary>
        [Test]
        public void V1CompaniesByIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //var response = instance.V1CompaniesByIdGet(id);
            //Assert.IsInstanceOf<Company> (response, "response is Company");
        }
        
        /// <summary>
        /// Test V1CompaniesByIdPut
        /// </summary>
        [Test]
        public void V1CompaniesByIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //Company value = null;
            //instance.V1CompaniesByIdPut(id, value);
            
        }
        
        /// <summary>
        /// Test V1CompaniesGet
        /// </summary>
        [Test]
        public void V1CompaniesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1CompaniesGet();
            //Assert.IsInstanceOf<List<Company>> (response, "response is List<Company>");
        }
        
        /// <summary>
        /// Test V1CompaniesPost
        /// </summary>
        [Test]
        public void V1CompaniesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Company value = null;
            //instance.V1CompaniesPost(value);
            
        }
        
    }

}
