/* 
 * EmployeeManagementSystem API
 *
 * Simple web app with open API for Euristiq needs
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EmployeesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EmployeesApiTests
    {
        private EmployeesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EmployeesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EmployeesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EmployeesApi
            //Assert.IsInstanceOfType(typeof(EmployeesApi), instance, "instance is a EmployeesApi");
        }

        
        /// <summary>
        /// Test V1EmployeesByIdDelete
        /// </summary>
        [Test]
        public void V1EmployeesByIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //instance.V1EmployeesByIdDelete(id);
            
        }
        
        /// <summary>
        /// Test V1EmployeesByIdGet
        /// </summary>
        [Test]
        public void V1EmployeesByIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //var response = instance.V1EmployeesByIdGet(id);
            //Assert.IsInstanceOf<Employee> (response, "response is Employee");
        }
        
        /// <summary>
        /// Test V1EmployeesByIdPut
        /// </summary>
        [Test]
        public void V1EmployeesByIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //Employee value = null;
            //instance.V1EmployeesByIdPut(id, value);
            
        }
        
        /// <summary>
        /// Test V1EmployeesGet
        /// </summary>
        [Test]
        public void V1EmployeesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1EmployeesGet();
            //Assert.IsInstanceOf<List<Employee>> (response, "response is List<Employee>");
        }
        
        /// <summary>
        /// Test V1EmployeesPost
        /// </summary>
        [Test]
        public void V1EmployeesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Employee value = null;
            //instance.V1EmployeesPost(value);
            
        }
        
    }

}
