/* 
 * EmployeeManagementSystem API
 *
 * Simple web app with open API for Euristiq needs
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Company
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CompanyTests
    {
        // TODO uncomment below to declare an instance variable for Company
        //private Company instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Company
            //instance = new Company();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Company
        /// </summary>
        [Test]
        public void CompanyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Company
            //Assert.IsInstanceOfType<Company> (instance, "variable 'instance' is a Company");
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Employees'
        /// </summary>
        [Test]
        public void EmployeesTest()
        {
            // TODO unit test for the property 'Employees'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Test]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }

    }

}
